
export const ORDER_TYPES={
    SET_CLIENT_TYPE:'order/CLIENT_TYPE',
    SET_PAYMENT_TYPE:'order/PAYMENT_TYPE',
    SET_ORDER_DATA:'order/SET_ORDER_DATA',
    SET_TOTAL:'order/SET_TOTAL',
    SET_PRODUCTS:'order/SET_PRODUCTS',
    SET_ORDER_SENT:'order/SET_ORDER_SENT',
    SET_ORDER_UID:'order/SET_ORDER_UID',
    SET_ORDER_CLEAR:'order/SET_ORDER_CLEAR',
    SET_ORDER_DATE:'order/SET_ORDER_DATE',
    
    
    SET_ORDER_TO_COLLECTION_START:'order/SET_ORDER_TO_COLLECTION_START',
    SET_ORDER_TO_COLLECTION_SUCCES:'order/SET_ORDER_TO_COLLECTION_SUCCES',
    SET_ORDER_TO_COLLECTION_FAILD:'order/SET_ORDER_TO_COLLECTION_FAILD'
}
