
export const DIRECTORY_CATEGORIES_TYPES={
    FETCH_DIRECTORY_CATEGORIES_START:'directory/FETCH_DIRECTORY_CATEGORIES_START',
    FETCH_DIRECTORY_CATEGORIES_SUCCES:'directory/FETCH_DIRECTORY_CATEGORIES_SUCCES',
    FETCH_DIRECTORY_CATEGORIES_FAILD:'directory/FETCH_DIRECTORY_CATEGORIES_FAILD'

}
