export const CURRENT_USER_TYPES={
    
    CHECH_USER_SESSION:'user/CHECH_USER_SESSION',
    GOOGLE_SIGN_IN_POP_UP_START:'user/GOOGLE_SIGN_IN_POP_UP_START',
    GOOGLE_SIGN_IN_REDIRECT:'user/GOOGLE_SIGN_IN_REDIRECT',
    EMAIL_SIGN_IN_START:'user/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCES:'user/SIGN_IN_SUCCES',
    SIGN_IN_FAILD:'user/SIGN_IN_FAILD',
    SIGN_UP_START:'user/ SIGN_UP_START',
    SIGN_UP_FAILD:'user/SIGN_UP_FAILD',
    SIGN_OUT_FAILD:'user/SIGN_OUT_FAILD',
    SIGN_OUT_SUCCES:'user/SIGN_OUT_SUCCES',
    SIGN_OUT_START:'user/SIGN_OUT_START',
   
    

    


    
 }
 