export const CART_ITEM_TYPES={
    SET_CART_ITEMS:'cart/SET_CART_ITEMS',
    SET_TOTAL_QUANTITY:'cart/SET_TOTAL_QUANTITY',
    SET_TOTAL_PRICE:'cart/SET_TOTAL_PRICE',
    SET_IS_CART_OPEN:'cart/SET_IS_CART_OPEN',
    SET_CLEAR_ALL:'cart/SET_CLEAR_ALL'
 }