export const CART_ITEM_TYPES={
    SET_CART_ITEMS:'CART/SET_CART_ITEMS',
    SET_TOTAL_QUANTITY:'CART/SET_TOTAL_QUANTITY',
    SET_TOTAL_PRICE:'CART/SET_TOTAL_PRICE',
    SET_IS_CART_OPEN:'CART/SET_IS_CART_OPEN',
 }